export var spanish = {
  "Welcome":"Bienvenido",
  "Home" : "Inicio",
  "Configuration": "Configuracion",
  "Log Out" : "Cerrar Session",
  "Current ApiKey":"Clave Actual",
  "Lenguage":"Idioma",
  "Break time":"Tiempo Descanso",
  "Company name":"Nombre Empresa",
  "Close Menu":"Cerrar Menu",
  "Name":"Nombre",
  "Workspace Id":"Id Espacio Trabajo",
  "Search":"Buscar",
  "Print table":"Imprimir Tabla",
  "Start Date":"Fecha Inicio",
  "Start 1ºTurn":"Inicio 1ºTurno",
  "End 1ºTurn":"Final 1ºTurno",
  "Start 2ºTurn":"Inicio 2ºTurno",
  "End 2ºTurn":"Final 2ºTurno",
  "Duration":"Duracion",
  "Year":"Año",
  "Month":"Mes",
  "January":"Enero",
  "Febuary":"Febrero",
  "March":"Marzo",
  "April":"Abril",
  "May":"Mayo",
  "June":"Junio",
  "July":"Julio",
  "August":"Agosto",
  "September":"Septiembre",
  "November":"Noviembre",
  "December":"Diciembre",
  "Save":"Guardar",
  "Chart":"Grafico",
  "New key":"Nueva clave",
  "Hour:min":"Hora:min",
  "New Name":"Nuevo Nombre",
  "New CIF":"Nuevo CIF",
  "Employee":"Empleado",
  "Log in with email":"Inicia session con correo",
  "Log in with Facebook":"Inicia sesion con Facebook",
  "LOG IN":"Iniciar sesion",
  "Don’t have an account?":"¿Aun no tienes cuenta?",
  "Sign up now":"Registrate Ahora",
  "Sign":"Firma"




}